apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.8-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 128Mi
