apiVersion: v1
kind: Service
metadata:
  name: demo-database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: todo
    tier: database
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app: todo
    tier: database
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: ZGVtby1wYXNzd29yZA==
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: todo
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-database
  labels:
    app: todo
    tier: database
spec:
  selector:
    matchLabels:
      app: todo
      tier: database
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo
        tier: database
    spec:
      containers:
      - image: postgres:13-alpine
        imagePullPolicy: IfNotPresent
        name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim