apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-list.fullname" . }}-frontend
  labels:
    {{- include "todo-list.labels" . | nindent 4 }}
    tier: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todo-list.selectorLabels" . | nindent 4 }}
    tier: frontend
